### ISSUE TITLE
2 repos for CSB

### ISSUE THREAD

**Issue by kelpisland** [BritishColumbia/CSB-eFile-src#1]
Hey Shea - do you plan on using the CSB-eFile repo I created as well or just this one? If the old repo isn't needed let me know and I'll delete it.

**Comment by sheaphillips** [comment]
We'll use both - the -src repo is for the "source" RAML and the other is for publishing the documentation that we generate - essentially a reference repository.  We have set up a cones integration job to build/generate from the -src repo and publish/push to the other.  We may end up wanting different permissions/collaborators for the two repos, but we'll leave as-is for now.

**Comment by kelpisland** [comment]
Awesome - thanks
